### ISSUE TITLE
libmxnet.so is libmxnet.dylib on OSX

### ISSUE THREAD

**Issue by kalinon** [toddsundsted/mxnet.cr#1]
Looks like the compiled version of mxnet outputs a `dylib` on OSX. Both the python package and compiling it from scratch generate this file. Since the link and python code look for the `.so` file specifically the shard dies on compliation.

Example paths:

`/usr/local/lib/python3.9/site-packages/mxnet/libmxnet.dylib`
`~/github.com/apache/incubator-mxnet/libmxnet.dylib`

replacing the ```@[Link(ldflags: "`python '#{__DIR__}/libmxnet.py' library`")]``` with: `@[Link(ldflags: "<dylib path>")]` works. The example code from https://github.com/toddsundsted/deep-learning also works with the dylib, so it is probably safe to look for either `.so` or `.dylib`

**Comment by toddsundsted** [comment]
thanks @kalinon let me take a look at that. the existing solution dates back to maybe pre-1.2.0 and maybe the `dylib` wasn't present, or maybe i didn't know how to make it work.

**Comment by toddsundsted** [comment]
@kalinon how are you installing mxnet? i last installed with miniconda and that seems to provide the `*.so`

**Comment by toddsundsted** [comment]
e117d0b should fix this.

i should probably just use `libinfo.py`.

**Comment by kalinon** [comment]
@toddsundsted sorry for the late response. So to get mxnet installed i first installed it via `pip3 install mxnet` but that didnt give me a `.so` so I ended up compiling it manually.

```
$ pip3 list | grep mxnet
mxnet                 1.8.0.post0
```

**Comment by kalinon** [comment]
> [e117d0b](https://github.com/toddsundsted/mxnet.cr/commit/e117d0bf83c22c772312a10fe3a4210fa512fd85) should fix this.
> 
> i should probably just use `libinfo.py`.

Ill give it a try!

**Comment by toddsundsted** [comment]
thanks! let me know what happens. i'm happy to do more troubleshooting.

**Comment by kalinon** [comment]
@toddsundsted this worked. I had to link my `python3` to `python` but then i could then compile no problems. 👍
